version: '3.3'

services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'shop_online_manager_db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    volumes:
      # set the path for persistance
      - .db-data:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  my-datavolume: